name: CI

on:
  pull_request:
    branches:
      - master
  pull_request_target:
    branches:
      - master

permissions:
  contents: read
  pull-requests: write

jobs:
  # --- Job: Check for not allowed file changes (Safe, no checkout) ---
  check-not-allowed:
    if: github.event_name == 'pull_request_target'
    name: Check Not Allowed File Changes
    runs-on: ubuntu-latest
    steps:
      - name: Check file paths
        uses: dorny/paths-filter@v2
        id: filter_not_allowed
        with:
          list-files: json
          filters: |
            change:
              - 'package-lock.json'
              - 'yarn.lock'
              - 'pnpm-lock.yaml'

      - name: Comment About Changes We Can't Accept
        if: steps.filter_not_allowed.outputs.change == 'true'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "🚫 Your PR includes changes to lock files (`package-lock.json`, `yarn.lock`, or `pnpm-lock.yaml`), which are not allowed. Please remove them."
            })

  # --- Job: Markdown Lint (Safe, runs in PR context) ---
  lint-markdown:
    if: github.event_name == 'pull_request'
    name: Lint Markdown
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR code
        uses: actions/checkout@v3

      - name: Lint Markdown files
        run: npx markdownlint-cli '**/*.md' --ignore node_modules