name: MC Docu CI

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 360
    continue-on-error: ${{ matrix.experimental }}

    strategy:
      fail-fast: true
      max-parallel: 2
      matrix:
        node-version: [16.x, 18.x, 20.x]
        experimental: [false]
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm install
      - name: Build Release Files
        run: npm run build --if-present
      - name: Electronegativity
        uses: doyensec/electronegativity-action@v2.0
      - name: Build for Windows
        if: startsWith(matrix.os, 'windows')
        run: npm run build:win
      - name: Build for macOS
        if: startsWith(matrix.os, 'macos')
        run: npm run build:mac
      - name: Build for Linux
        if: startsWith(matrix.os, 'ubuntu')
        run: npm run build:linux
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: release_on_${{ matrix.os }}_node_${{ matrix.node-version }}
          path: dist/
          retention-days: 5
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: release_on_${{ matrix.os }}_node_${{ matrix.node-version }}
          path: dist/