name: MC Docu CI

on:
  push:
    branches: ['master']
    paths-ignore:
      - '**.md'
      - '**.spec.js'
      - '.idea'
      - '.vscode'
      - '.dockerignore'
      - 'Dockerfile'
      - '.gitignore'
      - '.github/**'
      - '!.github/workflows/build.yml'
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 360

    strategy:
      fail-fast: true
      max-parallel: 4
      matrix:
        version: ['latest']
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
          cache: npm

      - name: Install Dependencies
        run: npm install --force

      - name: Build Release Files
        run: npm run build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Tests
        run: npm test

      - name: Electronegativity
        uses: doyensec/electronegativity-action@v2.0

      - name: Build for Windows
        if: matrix.os == 'windows-latest'
        run: npm run build:win

      - name: Build for macOS
        if: matrix.os == 'macos-latest'
        run: npm run build:mac

      - name: Build for Linux
        if: matrix.os == 'ubuntu-latest'
        run: npm run build:linux

      - name: List Release Files (Linux & macOS)
        if: runner.os != 'Windows'
        run: ls -la dist/

      - name: List Release Files (Windows)
        if: runner.os == 'Windows'
        run: dir dist

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: release_on_${{ matrix.os }}_node_${{ matrix.version }}
          path: dist/
          retention-days: 62
          if-no-files-found: warn

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: release_on_${{ matrix.os }}_node_${{ matrix.version }}
          path: dist/
